baseurl = "/"
languageCode = "en-us"
title = "Statistical Issues"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
ignoreFiles = ["\\.html$"] # igenore html and build from md

[params]
	# General information
	author = "Erick Chacon, Vilma Romero and Rommy Camasca"
	description = "A website about statistical modelling and related topics."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/statistical-issues/statistical-issues.github.io"

	version = ""
	logo = "images/bla.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["mycss.css"]
	# custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "statistical-issues"
	# email   = "hello@email.com"


# [[menu.main]]
# 	name   = "About"
# 	# url    = "about"
# 	weight = 1

[[menu.main]]
	name   = "Blog"
        url = "post"
	weight = 10

[[menu.main]]
	name   = "Statistics"
        url = "statistics/introduction"
	weight = 20

[[menu.main]]
	name   = "Inference"
        url = "inference/introduction"
	weight = 30

[[menu.main]]
	name   = "Modelling"
        url = "modelling/introduction"
	weight = 40

[[menu.main]]
	name   = "Computing"
        url = "computing/introduction"
	weight = 50

[[menu.main]]
	name   = "Software"
        url = "software/introduction"
	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
